# Generated by Django 2.2.4 on 2019-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20190828_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
