# Generated by Django 2.2.4 on 2019-08-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_city_city_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_code',
        ),
    ]
