# Generated by Django 2.2 on 2019-08-07 10:40

from django.db import migrations, models
import room_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimages',
            name='room_image',
            field=models.ImageField(blank=True, upload_to=room_service.models.upload_room_images),
        ),
    ]
