# Generated by Django 2.2 on 2019-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0002_auto_20190807_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
