# Generated by Django 2.2 on 2019-08-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0003_room_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='desciption',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='room_service.Room'),
        ),
    ]
