# Generated by Django 2.2 on 2019-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0004_auto_20190808_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='monthly_rent',
            field=models.CharField(max_length=10),
        ),
    ]
